

select * from Customers;

drop table Customers;

create table Customers(
  CustomerID int generated by default on null as identity,
  CustomerName varchar(40),
  ContactName varchar(30),
  Address varchar(30),
  City varchar(30),
  PostalCode varchar(30),
  Country varchar(30),
  primary key (CustomerID)
);

--1
insert into Customers (CustomerName,ContactName,Address,City,Postalcode,Country) 
values ('Alfreds Futterkiste','Maria Anders','Obere Str.57','Berlin','12209','Germany');
--2
insert into Customers (CustomerName,ContactName,Address,City,Postalcode,Country) 
values ('Ana Trujillo Emparedados y helados','Ana Trujillo','Avda. de la Constitución 2222','México D.F.','05021','Mexico');

--3
insert into Customers (CustomerName,ContactName,Address,City,Postalcode,Country) 
values ('Alfreds Futterkiste','Maria Anders','Obere Str.57','Berlin','12209','Germany');

--4
insert into Customers (CustomerName,ContactName,Address,City,Postalcode,Country) 
values ('Antonio Moreno Taquería','Antonio Moreno','Mataderos 2312','México D.F.','05023','Mexico');










